version: "3.8"
services:
  db:
    image: ankane/pgvector
    container_name: lumnia_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lumnia
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - lumnia

  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"
    networks:
      - lumnia

networks:
  lumnia:
    driver: bridge