import type { MenuItem } from '@/types/types'

export const menuItems: MenuItem[] = [
  {
    title: 'Tela inicial',
    route: '/home',
    admin: false,
    class: 'principal',
    icon: 'mdi-home',
  },
  {
    title: 'Chats',
    route: '/chats',
    permission: 'use_chats',
    class: 'principal',
    admin: false,
    icon: 'mdi-message-text-outline',
  },
  {
    title: 'Bases de conhecimento',
    route: '/knowledge-bases',
    permission: 'manage_knowledge_bases',
    class: 'operational',
    admin: false,
    icon: 'mdi-book-open-variant-outline',
  },
  {
    title: 'Usuários',
    route: '/users',
    class: 'admin',
    admin: true,
    permission: 'manage_users',
    icon: 'mdi-account',
  },
  {
    title: 'Grupos',
    route: '/groups',
    class: 'admin',
    admin: true,
    permission: 'manage_groups',
    icon: 'mdi-account-group',
  },
  {
    title: 'Permissões',
    route: '/permissions',
    class: 'admin',
    admin: true,
    permission: 'manage_permissions',
    icon: 'mdi-shield-key',
  },
  {
    title: 'Personas',
    route: '/personas',
    class: 'operational',
    admin: false,
    permission: 'manage_personas',
    icon: 'mdi-account-tie',
  },
  {
    title: 'Logs de erros',
    route: '/error-logs',
    class: 'logs',
    admin: true,
    permission: 'view_error_logs',
    icon: 'mdi-alert-circle-outline',
  },
  {
    title: 'Avaliação das respostas',
    route: '/reports-answers',
    class: 'reports',
    admin: true,
    permission: 'view_reports_answers',
    icon: 'mdi-file-chart',
  },
  {
    title: 'Métricas de uso',
    route: '/reports-metrics',
    class: 'reports',
    admin: true,
    permission: 'view_reports_metrics',
    icon: 'mdi-chart-bar',
  }
]
