version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

networks:
  app-network:
    driver: bridge
